<a href="https://colab.research.google.com/github/ANANTHA-KRISHNA-J/Parkinsons-disease-Prediction/blob/main/Parkinson's_Disease_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split as tts

In [ ]:
df = pd.read_csv('parkinsons.csv').dropna()
df.tail(10)

name  MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
185  phon_R01_S49_3      116.286       177.291        96.983         0.00314   
186  phon_R01_S49_4      116.556       592.030        86.228         0.00496   
187  phon_R01_S49_5      116.342       581.289        94.246         0.00267   
188  phon_R01_S49_6      114.563       119.167        86.647         0.00327   
189  phon_R01_S50_1      201.774       262.707        78.228         0.00694   
190  phon_R01_S50_2      174.188       230.978        94.261         0.00459   
191  phon_R01_S50_3      209.516       253.017        89.488         0.00564   
192  phon_R01_S50_4      174.688       240.005        74.287         0.01360   
193  phon_R01_S50_5      198.764       396.961        74.904         0.00740   
194  phon_R01_S50_6      214.289       260.277        77.973         0.00567   

     MDVP:Jitter(Abs)  MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  ...  \
185           0.00003   0.00134   0.00192     0.00403       0.01564  ...   
186           0.00004   0.00254   0.00263     0.00762       0.01660  ...   
187           0.00002   0.00115   0.00148     0.00345       0.01300  ...   
188           0.00003   0.00146   0.00184     0.00439       0.01185  ...   
189           0.00003   0.00412   0.00396     0.01235       0.02574  ...   
190           0.00003   0.00263   0.00259     0.00790       0.04087  ...   
191           0.00003   0.00331   0.00292     0.00994       0.02751  ...   
192           0.00008   0.00624   0.00564     0.01873       0.02308  ...   
193           0.00004   0.00370   0.00390     0.01109       0.02296  ...   
194           0.00003   0.00295   0.00317     0.00885       0.01884  ...   

     Shimmer:DDA      NHR     HNR  status      RPDE       DFA   spread1  \
185      0.02001  0.00737  24.199       0  0.598515  0.654331 -5.592584   
186      0.02460  0.01397  23.958       0  0.566424  0.667654 -6.431119   
187      0.01892  0.00680  25.023       0  0.528485  0.663884 -6.359018   
188      0.01672  0.00703  24.775       0  0.555303  0.659132 -6.710219   
189      0.04363  0.04441  19.368       0  0.508479  0.683761 -6.934474   
190      0.07008  0.02764  19.517       0  0.448439  0.657899 -6.538586   
191      0.04812  0.01810  19.147       0  0.431674  0.683244 -6.195325   
192      0.03804  0.10715  17.883       0  0.407567  0.655683 -6.787197   
193      0.03794  0.07223  19.020       0  0.451221  0.643956 -6.744577   
194      0.03078  0.04398  21.209       0  0.462803  0.664357 -5.724056   

      spread2        D2       PPE  
185  0.133917  2.058658  0.214346  
186  0.153310  2.161936  0.120605  
187  0.116636  2.152083  0.138868  
188  0.149694  1.913990  0.121777  
189  0.159890  2.316346  0.112838  
190  0.121952  2.657476  0.133050  
191  0.129303  2.784312  0.168895  
192  0.158453  2.679772  0.131728  
193  0.207454  2.138608  0.123306  
194  0.190667  2.555477  0.148569  

[10 rows x 24 columns]

In [ ]:
df.describe()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  \
count   195.000000    195.000000    195.000000      195.000000   
mean    154.228641    197.104918    116.324631        0.006220   
std      41.390065     91.491548     43.521413        0.004848   
min      88.333000    102.145000     65.476000        0.001680   
25%     117.572000    134.862500     84.291000        0.003460   
50%     148.790000    175.829000    104.315000        0.004940   
75%     182.769000    224.205500    140.018500        0.007365   
max     260.105000    592.030000    239.170000        0.033160   

       MDVP:Jitter(Abs)    MDVP:RAP    MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  \
count        195.000000  195.000000  195.000000  195.000000    195.000000   
mean           0.000044    0.003306    0.003446    0.009920      0.029709   
std            0.000035    0.002968    0.002759    0.008903      0.018857   
min            0.000007    0.000680    0.000920    0.002040      0.009540   
25%            0.000020    0.001660    0.001860    0.004985      0.016505   
50%            0.000030    0.002500    0.002690    0.007490      0.022970   
75%            0.000060    0.003835    0.003955    0.011505      0.037885   
max            0.000260    0.021440    0.019580    0.064330      0.119080   

       MDVP:Shimmer(dB)  ...  Shimmer:DDA         NHR         HNR      status  \
count        195.000000  ...   195.000000  195.000000  195.000000  195.000000   
mean           0.282251  ...     0.046993    0.024847   21.885974    0.753846   
std            0.194877  ...     0.030459    0.040418    4.425764    0.431878   
min            0.085000  ...     0.013640    0.000650    8.441000    0.000000   
25%            0.148500  ...     0.024735    0.005925   19.198000    1.000000   
50%            0.221000  ...     0.038360    0.011660   22.085000    1.000000   
75%            0.350000  ...     0.060795    0.025640   25.075500    1.000000   
max            1.302000  ...     0.169420    0.314820   33.047000    1.000000   

             RPDE         DFA     spread1     spread2          D2         PPE  
count  195.000000  195.000000  195.000000  195.000000  195.000000  195.000000  
mean     0.498536    0.718099   -5.684397    0.226510    2.381826    0.206552  
std      0.103942    0.055336    1.090208    0.083406    0.382799    0.090119  
min      0.256570    0.574282   -7.964984    0.006274    1.423287    0.044539  
25%      0.421306    0.674758   -6.450096    0.174351    2.099125    0.137451  
50%      0.495954    0.722254   -5.720868    0.218885    2.361532    0.194052  
75%      0.587562    0.761881   -5.046192    0.279234    2.636456    0.252980  
max      0.685151    0.825288   -2.434031    0.450493    3.671155    0.527367  

[8 rows x 23 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 24 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   name              195 non-null    object 
 1   MDVP:Fo(Hz)       195 non-null    float64
 2   MDVP:Fhi(Hz)      195 non-null    float64
 3   MDVP:Flo(Hz)      195 non-null    float64
 4   MDVP:Jitter(%)    195 non-null    float64
 5   MDVP:Jitter(Abs)  195 non-null    float64
 6   MDVP:RAP          195 non-null    float64
 7   MDVP:PPQ          195 non-null    float64
 8   Jitter:DDP        195 non-null    float64
 9   MDVP:Shimmer      195 non-null    float64
 10  MDVP:Shimmer(dB)  195 non-null    float64
 11  Shimmer:APQ3      195 non-null    float64
 12  Shimmer:APQ5      195 non-null    float64
 13  MDVP:APQ          195 non-null    float64
 14  Shimmer:DDA       195 non-null    float64
 15  NHR               195 non-null    float64
 16  HNR               195 non-null    float64
 1

In [ ]:
X = df.drop(columns=['name','status'],axis=1)
y = df.status

In [ ]:
X.head()

MDVP:Fo(Hz)  MDVP:Fhi(Hz)  MDVP:Flo(Hz)  MDVP:Jitter(%)  MDVP:Jitter(Abs)  \
0      119.992       157.302        74.997         0.00784           0.00007   
1      122.400       148.650       113.819         0.00968           0.00008   
2      116.682       131.111       111.555         0.01050           0.00009   
3      116.676       137.871       111.366         0.00997           0.00009   
4      116.014       141.781       110.655         0.01284           0.00011   

   MDVP:RAP  MDVP:PPQ  Jitter:DDP  MDVP:Shimmer  MDVP:Shimmer(dB)  ...  \
0   0.00370   0.00554     0.01109       0.04374             0.426  ...   
1   0.00465   0.00696     0.01394       0.06134             0.626  ...   
2   0.00544   0.00781     0.01633       0.05233             0.482  ...   
3   0.00502   0.00698     0.01505       0.05492             0.517  ...   
4   0.00655   0.00908     0.01966       0.06425             0.584  ...   

   MDVP:APQ  Shimmer:DDA      NHR     HNR      RPDE       DFA   spread1  \
0   0.02971      0.06545  0.02211  21.033  0.414783  0.815285 -4.813031   
1   0.04368      0.09403  0.01929  19.085  0.458359  0.819521 -4.075192   
2   0.03590      0.08270  0.01309  20.651  0.429895  0.825288 -4.443179   
3   0.03772      0.08771  0.01353  20.644  0.434969  0.819235 -4.117501   
4   0.04465      0.10470  0.01767  19.649  0.417356  0.823484 -3.747787   

    spread2        D2       PPE  
0  0.266482  2.301442  0.284654  
1  0.335590  2.486855  0.368674  
2  0.311173  2.342259  0.332634  
3  0.334147  2.405554  0.368975  
4  0.234513  2.332180  0.410335  

[5 rows x 22 columns]

In [ ]:
df['status'].value_counts()

status
1    147
0     48
Name: count, dtype: int64

In [ ]:
df.dtypes

name                 object
MDVP:Fo(Hz)         float64
MDVP:Fhi(Hz)        float64
MDVP:Flo(Hz)        float64
MDVP:Jitter(%)      float64
MDVP:Jitter(Abs)    float64
MDVP:RAP            float64
MDVP:PPQ            float64
Jitter:DDP          float64
MDVP:Shimmer        float64
MDVP:Shimmer(dB)    float64
Shimmer:APQ3        float64
Shimmer:APQ5        float64
MDVP:APQ            float64
Shimmer:DDA         float64
NHR                 float64
HNR                 float64
status                int64
RPDE                float64
DFA                 float64
spread1             float64
spread2             float64
D2                  float64
PPE                 float64
dtype: object

In [ ]:
ss = StandardScaler()
X = ss.fit_transform(X)

In [ ]:
X[2]

array([-0.90947638, -0.7231683 , -0.10987483,  0.88499086,  1.3255889 ,
        0.72076961,  1.58568688,  0.72181312,  1.2026929 ,  1.02763576,
        1.17564285,  1.72617584,  0.69918677,  1.17532274, -0.29163266,
       -0.27976031, -0.66207509,  1.94204837,  1.14144541,  1.01768236,
       -0.10362861,  1.40266141])

In [ ]:
X_train,X_test,y_train,y_test = tts(X,y,test_size=0.25,random_state=6,stratify=y)

In [ ]:
print(X.shape , X_train.shape , X_test.shape , y_test.shape)

(195, 22) (146, 22) (49, 22) (49,)


In [ ]:
model = SVC(kernel='sigmoid')
model.fit(X_train,y_train)

SVC(kernel='sigmoid')

In [ ]:
pred_y = model.predict(X_test)
acc = accuracy_score(y_test,pred_y)

In [ ]:
print('Accuracy',acc)

Accuracy 0.8979591836734694


In [ ]:
print("Classification report ",classification_report(y_test,pred_y))

Classification report                precision    recall  f1-score   support

           0       1.00      0.58      0.74        12
           1       0.88      1.00      0.94        37

    accuracy                           0.90        49
   macro avg       0.94      0.79      0.84        49
weighted avg       0.91      0.90      0.89        49



In [ ]:
inp_data = (116.676, 137.871, 111.366, 0.00997, 0.00009, 0.00502, 0.00698, 0.01505, 0.05492, 0.517, 0.02924, 0.04005, 0.03772, 0.08771, 0.01353, 20.644,0.434969, 0.819235, -4.117501, 0.334147, 2.405554, 0.368975)
inp_data2 = (174.188, 230.978, 94.261, 0.00459, 0.00003, 0.00263, 0.00259, 0.00790, 0.04087, 0.405, 0.02336, 0.02498, 0.02745, 0.07008, 0.02764, 19.517,0.448439, 0.657899, -6.538586, 0.121952, 2.657476, 0.133050)
asnumar = np.asarray(inp_data)
asnumar2 = np.asarray(inp_data2).reshape(1,-1)
asnumar2

array([[ 1.741880e+02,  2.309780e+02,  9.426100e+01,  4.590000e-03,
         3.000000e-05,  2.630000e-03,  2.590000e-03,  7.900000e-03,
         4.087000e-02,  4.050000e-01,  2.336000e-02,  2.498000e-02,
         2.745000e-02,  7.008000e-02,  2.764000e-02,  1.951700e+01,
         4.484390e-01,  6.578990e-01, -6.538586e+00,  1.219520e-01,
         2.657476e+00,  1.330500e-01]])

In [ ]:
reshaped = asnumar.reshape(1,-1)
reshaped

array([[ 1.166760e+02,  1.378710e+02,  1.113660e+02,  9.970000e-03,
         9.000000e-05,  5.020000e-03,  6.980000e-03,  1.505000e-02,
         5.492000e-02,  5.170000e-01,  2.924000e-02,  4.005000e-02,
         3.772000e-02,  8.771000e-02,  1.353000e-02,  2.064400e+01,
         4.349690e-01,  8.192350e-01, -4.117501e+00,  3.341470e-01,
         2.405554e+00,  3.689750e-01]])

In [ ]:
std = ss.fit_transform(reshaped)

In [ ]:
pred = model.predict(reshaped)
pred

array([1])

In [ ]:
pred = model.predict(asnumar2)
pred

array([0])

In [ ]:
std2 = ss.fit_transform(asnumar2)

In [ ]:
if (pred[0] == 0):
  print("The Person does not have Parkinsons Disease")

else:
  print("The Person has Parkinsons")


The Person does not have Parkinsons Disease


In [ ]:
import pickle
parkinsons = 'parksinsons.sav'
pickle.dump(model,open(parkinsons,'wb'))
loaded_model = pickle.load(open(parkinsons,'rb'))